### ISSUE TITLE
Optional and OptionalAt succeed if you pass an array instead of an object

### ISSUE THREAD

**Issue by MangelMaxime** [NoRedInk/elm-decode-pipeline#40]
Demo: https://ellie-app.com/rLTx9CFkcKa1

Code:

```elm
module Main exposing (main)

import Html exposing (Html)

import Json.Decode exposing (int, string, float, nullable, Decoder)
import Json.Decode.Pipeline exposing (decode, required, optional, hardcoded)


type alias User =
  { id : Int
  , name : String
  }


userDecoder : Decoder User
userDecoder =
  decode User
    |> optional "id" int 0
    |> optional "name" string ""

result =
    Json.Decode.decodeString
        userDecoder
        "[]"

main : Html msg
main =
    case result of 
    Ok v -> Html.text (Basics.toString v)
    Err err -> Html.text err
```

This should output an error telling us that we didn't pass an object.

Note in JavaScript to test if a value is an object we need to do: 

```js
typeof value === 'object' && (value !== null) && value.constructor === Object
```

`value.constructor === Object` is important because `typeof []` give `object`

**Comment by rtfeldman** [comment]
Great find!

This is happening because `optional` and `optionalAt` first attempt to decode the field in question using `Decode.value`, and if that fails, they assume it was because the field was missing. They don't account for the possibility that decoding the field failed because they weren't looking at an object!
